name: Binary

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
        check-latest: true

    - name: Make
      run: make
    
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true